<?php
class MetaBox extends Core
{
/**
 * Generated by the WordPress Meta Box generator
 * at http://jeremyhixon.com/tool/wordpress-meta-box-generator/
 */

	/**
	 * addMetaBox
	 *
	 *@author Golga <r-ro@bulko.net>
	 *@see http://jeremyhixon.com/tool/wordpress-meta-box-generator/
	 */
	public function addMetaBox()
	{
		add_meta_box(
			'champ_supplmentaire-champ-supplmentaire',
			__( 'Champ supplémentaire', 'champ_supplmentaire' ),
			array( $this, 'champHtml' ),
			'page',
			'normal',
			'default'
		);
	}

	/**
	 * champHtml
	 *
	 *@author Golga <r-ro@bulko.net>
	 *@see http://jeremyhixon.com/tool/wordpress-meta-box-generator/
	 */
	public function champHtml( WP_Post $post )
	{
		wp_nonce_field( '_champ_supplmentaire_nonce', 'champ_supplmentaire_nonce' ); ?>

		<p>
			<label for="aa_right_block"><?php _e( 'Colone de droite', 'champ_supplmentaire' ); ?></label><br>
			<?php wp_editor(
				htmlspecialchars_decode( $this->getMeta( 'aa_right_block' ) ),
				"aa_right_block",
				array(
					'textarea_rows'=>12,
					'editor_class'=>'aa_right_block')
				);
			?>
		</p><?php
	}

	/**
	 * saveMetaData
	 *
	 *@author Golga <r-ro@bulko.net>
	 *@see http://jeremyhixon.com/tool/wordpress-meta-box-generator/
	 */
	public function saveMetaData( Int $post_id )
	{
		if (
			( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE )
			|| ! isset( $_POST['champ_supplmentaire_nonce'] ) || ! wp_verify_nonce( $_POST['champ_supplmentaire_nonce'], '_champ_supplmentaire_nonce' )
			|| ! current_user_can( 'edit_post', $post_id )
		)
		{
			return;
		}
		if ( isset( $_POST['aa_right_block'] ) )
		{
			update_post_meta( $post_id, 'aa_right_block', esc_attr( $_POST['aa_right_block'] ) );
		}
	}
}
?>
